name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          if [ -n "${{ github.base_ref }}" ]; then
            echo "##[set-output name=branch;]${{ github.base_ref }}"
          else
            github_ref=${{ github.ref }}
            echo "##[set-output name=branch;]${github_ref##*/}"
          fi
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make -j
          make install
      - name: Package
        if: github.event_name == 'push'
        run: |
          cd build
          mkdir -p artifacts
          tar czf artifacts/cmake-shared.tar.gz -T install_manifest.txt
      - name: Archive result
        if: github.event_name == 'push'
        uses: liri-infra/github-action-upload-bintray@master
        with:
          file: build/artifacts/cmake-shared.tar.gz
          api_user: ${{ secrets.BINTRAY_API_USER }}
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository_user: liri
          repository: artifacts-${{ steps.extract_branch.outputs.branch }}
          package: cmake-shared
          version: '1.0'
          delete_file: true
          recreate_version: true
          calculate_metadata: false
          publish: '1'
